---
name: SQL-ReservedWords-PostgreSQL
version: 0.2
author:
  - 'Christian Hansen C<ch@ngmedia.com>'
abstract: Reserved SQL words by PostgreSQL
license: perl
requires:
  Sub::Exporter: 0
build_requires:
  Test::More: 0
provides:
  SQL::ReservedWords::PostgreSQL:
    file: lib/SQL/ReservedWords/PostgreSQL.pm
    version: 0.2
generated_by: Module::Build version 0.2611
